all: hello control types class memory references

references: references.d
	dmd references.d -of=references

memory: memory.d
	dmd memory.d -of=memory

class: class.d
	dmd class.d -of=class

hello: hello.d
	dmd hello.d -of=hello

control: control.d
	dmd control.d -of=control

types: types.d
	dmd types.d -of=types

clean:
	rm -f hello hello.o
